server:
  port: 7101

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/snowofcloud/spring-cloud-config.git  #自己的github
#          uri: https://github.com/enjoyeud/microconfig.git  #暂时用老师的github