server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://adminn:enjoy@eureka1:7001/eureka,http://adminn:enjoy@eureka2:7002/eureka,http://adminn:enjoy@eureka3:7003/eureka
#    register-with-eureka: false    不让其注册到eureka中
  instance:
    instance-id: spring-cloud-zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）

spring:
  zipkin:
    base-url: http://localhost:8601 #所有的数据提交到此服务之中
    sender:
      #      type: web       #提交的类型是web 服务
      type: rabbit       #提交的类型是web 服务
  sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率，默认为0.1
  application:
    name:  spring-cloud-zuul-gateway
  security:
    user:
      name: adminn
      password: enjoy

#zuul:
#  routes:
#    spring-cloud-users:  /users-proxy/**
#  ignored-services:
#    # 忽略掉用户服务的名称
##    spring-cloud-users  #这种方式也可以，但真实情况下，一般会有很多微服务，如果完全按照上面的配置方式会非常的麻烦，所有最加到的做法是可以采用一个通配符“*”的模式来统一完成。的模式来统一完成
#    "*"

#
#zuul:
#  routes:
#    users.path: /users-proxy/**
#    users.serviceId: spring-cloud-users
#  ignored-services:
#    "*"


#这是公共前缀
zuul:
  routes:
    users:
      path: /users-proxy/**
      serviceId: spring-cloud-users
    users2:
      path: /users2-proxy/**
      url: http://localhost:8090/
    product:
      path: /product-proxy/**
      serviceId: spring-cloud-product
  ignored-services:
    "*"
  prefix: /enjoy-api



