server:
  port: 80

#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://adminn:enjoy@eureka1:7001/eureka,http://adminn:enjoy@eureka2:7002/eureka,http://adminn:enjoy@eureka3:7003/eureka

ribbon:
  eureka:
    enabled: false

SPRING-CLOUD-PRODUCT:
  ribbon:
    listOfServers: http://localhost:8080,http://localhost:8082,http://localhost:8083






