server:
  port: 8601
spring:
  application:
    name: spring-cloud-zipkin-server


management:
  metrics:
    web:
      server:
        auto-time-requests: false #自动检查

zipkin:
  collector:
    sample-rate: 1.0
    http:
      enabled: false
    rabbitmq:
      addresses: localhost
      port: 15672
      password: 123456
      queue: zipkin
      username: enjoy
      virtual-host: /
  storage:
    type: mysql
    mysql:
      host: localhost
      port: 3306
      username: root2
      password: 123456
      db: zipkin

